#!/usr/bin/env bash
# Install Anki push + review-back sync (RFC-009 §5): a wrapper + a systemd --user timer (every 6h).
# Uses the bundled Anki desktop python. No-ops with a warning if Anki isn't installed. Idempotent.
set -euo pipefail
R="${1:-$HOME/hermes-university}"; V="${2:-$HOME/vault}"
PY=$(ls /usr/local/share/anki/python/bin/python3* 2>/dev/null | head -1 || true)
if [ -z "$PY" ]; then
  echo "  Anki backend not found (/usr/local/share/anki) — install Anki desktop to enable SRS sync. Skipping."
  exit 0
fi
mkdir -p "$HOME/.hermes/bin"
cat > "$HOME/.hermes/bin/hermes_anki_sync.sh" <<EOF
#!/usr/bin/env bash
# Push queued SRS cards to AnkiWeb + pull review results back (RFC-009 §5). Generated by install.
set -uo pipefail
set -a; . $R/config.env 2>/dev/null || true; . $HOME/.hermes/.env 2>/dev/null || true; set +a
export AW_USER="\${ANKIWEB_USERNAME:-}" AW_PASS="\${ANKIWEB_PASSWORD:-}"
COLL="\$(ls "$HOME/.local/share/Anki2"/*/collection.anki2 2>/dev/null | head -1)"
[ -n "\$COLL" ] || { echo "no Anki collection yet"; exit 0; }
"$PY" "$R/scripts/anki_sync.py" "$V" "\$COLL"
"$PY" "$R/scripts/anki_review_pull.py" "$V" "\$COLL" "$R/.venv/bin/hu-engine"
EOF
chmod +x "$HOME/.hermes/bin/hermes_anki_sync.sh"
UD="$HOME/.config/systemd/user"; mkdir -p "$UD"
cat > "$UD/hermes-anki-sync.service" <<EOF
[Unit]
Description=Hermes University — Anki push + review-back
After=network-online.target
[Service]
Type=oneshot
ExecStart=%h/.hermes/bin/hermes_anki_sync.sh
EOF
cat > "$UD/hermes-anki-sync.timer" <<EOF
[Unit]
Description=Anki sync every 6h
[Timer]
OnCalendar=*-*-* 03,09,15,21:00:00
Persistent=true
[Install]
WantedBy=timers.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now hermes-anki-sync.timer >/dev/null 2>&1 || true
echo "  installed anki-sync timer (python: $PY)"
